version: "3.9"

volumes:
  postgres_volume:
    driver: local

services:
  postgres:
    image: "postgres:13.3"
    container_name: "java-postgres"
    volumes:
      - postgres_volume:/var/lib/postgrevolume/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9090:9090"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka0:29090,LISTENER_EXTERNAL://localhost:9090
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  name-generator:
    build: ./name-generator
    depends_on:
      - postgres
      - kafka0
    container_name: "name-generator"
    ports:
      - "8081:8081"

  user-service:
    build: ./user-service
    depends_on:
      - postgres
      - kafka0
    container_name: "user-service"
    ports:
      - "8082:8082"

  pet-registration-service:
    build: ./pet-registration-service
    depends_on:
      - postgres
    environment:
      - NAME_GENERATOR_URL=http://name-generator:8081/
    container_name: "pet-registration-service"
    ports:
      - "8083:8083"