server:
  port: 8081

spring:
  application:
    name: name-generator
  liquibase:
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka0:29090
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: user-events

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
